name = "MicrosimAPIv1"
uuid = "9dd566b3-1809-4601-ae07-3fe8bab2468b"
authors = ["Graham Stark"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Genie = "c43c736e-a2d1-11e8-161f-af95117fbd1e"
GenieCache = "dec2e30d-c3e4-4386-8d4a-5e4ccb406543"
GenieSession = "03cc5b98-4f21-4eb6-99f2-22eced81f962"
GenieSessionFileSession = "5c4fdc26-39e3-47cf-9034-e533e09961c2"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Inflector = "6d011eab-0732-4556-8808-e463c76bf3b6"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Jedis = "b89ccfe0-2c5f-46f6-b89b-da3e1c2e286f"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Redis = "0cf705f9-a9e2-50d1-a699-2b372a39b750"
ScottishTaxBenefitModel = "a734f2ee-4b7f-478f-84ca-797081d39f6e"
StructTypes = "856f2bd8-1eba-4b0a-8007-ebc267875bd4"
SwagUI = "bf05d729-34b2-4f1f-a2f1-2452bece7ebc"
SwaggerMarkdown = "1b6eb727-ad4b-44eb-9669-b9596a6e760f"
UUIDs = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[sources]
ScottishTaxBenefitModel = {url = "https://github.com/grahamstark/ScottishTaxBenefitModel.jl"}

[compat]
DataFrames = "1,2"
DataStructures = "0,1"
Dates = "1"
Genie = "5,6"
GenieCache = "2,3"
GenieSession = "1,2"
GenieSessionFileSession = "1,2"
HTTP = "1"
Inflector = "1,2"
JSON3 = "1"
Jedis = "0.3,0.4"
Logging = "1.11.0"
LoggingExtras = "1,2"
Markdown = "1"
Observables = "0,1"
Parameters = "0,1"
Random = "1"
Redis = "3,4"
ScottishTaxBenefitModel = "0,1"
StructTypes = "1,2"
SwagUI = "0.10.0"
SwaggerMarkdown = "0.3.0"
UUIDs = "1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[preferences.ScottishTaxBenefitModel]
aa_payment_rate = 1.0
ccode = ""
civil_payment_rate = 1.0
default_run_name = "sb-0.1.7"
do_indirect_tax_calculations = false
do_legal_aid = false
do_local_run = false
do_marginal_rates = true
do_replacement_rates = false
dump_frames = false
include_institutional_population = false
included_data_years = [2019, 2021, 2022, 2023]
indirect_method = "matching"
ineq_income_measure = "eq_bhc_net_income"
legal_aid_costs_strategy = "la_individual_costs"
legal_aid_probs_data = "civil-legal-aid-probs-scotland-map_to_slab"
local-artifact_server_upload_unix = "/mnt/data/ScotBen/local_artifacts/"
local-artifact_server_upload_windows = "/mnt/data/ScotBen/local_artifacts/"
local-artifact_server_url_unix = "file:///mnt/data/ScotBen/local_artifacts/"
local-artifact_server_url_windows = "file:///c:/data/"
lower_multiple = 0.62
means_tested_routing = "uc_full"
poverty_line_source = "pl_first_sys"
public-artifact_server_upload = "vw@virtual-worlds.biz:public_html/artifacts/"
public-artifact_server_url = "https://virtual-worlds.biz/artifacts/"
replacement_rate_hours = 30
target_nation = "N_Scotland"
to_q = 3
to_y = 2025
upper_multiple = 5.8
use_shs = true
wealth_method = "matching"
weighting_relative_to_ons_weights = false
weighting_strategy = "use_runtime_computed_weights"
weighting_target_year = 2025

[targets]
test = ["Test"]
